### ISSUE TITLE
v3 produces a blank screen when using h264 codec

### ISSUE THREAD

**Issue by Mondrethos** [m1k1o/neko#498]
Hello,

I've always used firefox:latest and it works great, have been using Neko for months without issue. I updated today and no matter which container I use (i've tried ungoogled chrome, firefox, etc) and I get a blank page. I went bank to firefox:2.9 manually and that seems to work again. I don't see anything odd in the logs.

**Comment by Mondrethos** [comment]
> This seems to be relevant error for firefox.
> 
> ```
> 2025-04-03 06:48:09,914 DEBG 'firefox' stdout output:
> [GFX1-]: glxtest: libpci missing
> 2025-04-03 06:48:10,045 DEBG 'firefox' stdout output:
> [Parent 10, Main Thread] WARNING: Failed to execute child process “update-desktop-database” (No such file or directory): 'glib warning', file /builds/worker/checkouts/gecko/toolkit/xre/nsSigHandlers.cpp:201
> 2025-04-03 06:48:10,045 DEBG 'firefox' stdout output:
> (firefox:10): GLib-GIO-WARNING **: 06:48:10.045: Failed to execute child process “update-desktop-database” (No such file or directory)
> ```
> 
> But I don't see firefox going to failed state. You can check that using this:
> 
> ```
> $ docker exec -it neko_server_dev supervisorctl
> firefox                          RUNNING   pid 50, uptime 0:01:24
> neko                             RUNNING   pid 11, uptime 0:01:25
> openbox                          RUNNING   pid 49, uptime 0:01:24
> pulseaudio                       RUNNING   pid 8, uptime 0:01:25
> x-server                         RUNNING   pid 9, uptime 0:01:25
> ```
> 
> You can also try to run firefox manually in the container:
> 
> $ docker exec -it neko bash
> root@c7f279d79992:/# su neko
> neko@c7f279d79992:/$ firefox 
> [GFX1-]: glxtest: libpci missing

I'll give it a shot as soon as possible but that was just firefox on latest. The issue happens with chrome browsers as well. The issue goes away if I go back to 2.9

**Comment by m1k1o** [comment]
I noticed now that you specified `NEKO_VIDEO_CODEC` with h264 but neko created vp8 pipeline announcing it as h264.

```
6:48AM INF creating pipeline codec=h264 id=main module=capture src="... vp8enc ..." submodule=stream-sink
```

Fixed here: https://github.com/m1k1o/neko/commit/a75424d2f3e47dbffd7adb25f50c3bc2ef0215ca

You can (soon) test the image at `docker.io/m1k1o/neko:latest`. I'll be releasing it to ghcr.io by the end of the day.

**Comment by Mondrethos** [comment]
> I noticed now that you specified `NEKO_VIDEO_CODEC` with h264 but neko created vp8 pipeline announcing it as h264.
> 
> ```
> 6:48AM INF creating pipeline codec=h264 id=main module=capture src="... vp8enc ..." submodule=stream-sink
> ```
> 
> Fixed here: [a75424d](https://github.com/m1k1o/neko/commit/a75424d2f3e47dbffd7adb25f50c3bc2ef0215ca)
> 
> You can (soon) test the image at `docker.io/m1k1o/neko:latest`. I'll be releasing it to ghcr.io by the end of the day.

I've switched back to firefox:latest image and the issue is still persistent. Please let me know if I should do something else or send over the log again.

**Comment by m1k1o** [comment]
Please note, that this is currently available at `m1k1o/neko:latest` to test, not yet on `ghcr.io/m1k1o/neko:latest` as described in [Naming Convention](https://neko.m1k1o.net/docs/v3/installation/docker-images#naming).

**Comment by Mondrethos** [comment]
> Please note, that this is currently available at `m1k1o/neko:latest` to test, not yet on `ghcr.io/m1k1o/neko:latest` as described in [Naming Convention](https://neko.m1k1o.net/docs/v3/installation/docker-images#naming).

Ah, I see. I apologize for my misunderstanding.

**Comment by m1k1o** [comment]
Fix available in `ghcr.io/m1k1o/neko:latest`.
